### ISSUE TITLE
Implement unit test coverage

### ISSUE THREAD

**Issue by britram** [fp7mplane/protocol-ri#19]
Implement tests.py (currently in sdk-test branch) to maximize coverage of unit tests for the SDK.

**Comment by britram** [comment]
@MKV21 will handle testing of registry features (in model.py:test_registry())

**Comment by MKV21** [comment]
@britram can you look at my commit a78ca32 and tell me if it is okay what I have done in Registry._parse_from_uri(...)? This makes it possible to use files in the registry without using file://, otherwise it would not be possible to include relative paths like "../tests/registry.json" as it is not okay to write "file://../tests/resgistry.json".

**Comment by cimere** [comment]
@britram can you look at the [tests branch](https://github.com/fp7mplane/protocol-ri/tree/sdk-tests/tests) and tell me if it's ok? The Azn module has 100% coverage, meanwhile the tls module reaches 97% coverage.

**Comment by britram** [comment]
@cimere tests in tests/test.py seem to pass. 

@MKV21 tests in mplane,model fail, apparently because there is an assumption about paths somewhere which doesn't hold (the file you're looking for is at 'Users/brian/work/protocol-ri/tests/registry_with_parent.json); see error below.

======================================================================
ERROR: mplane.model.test_registry
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1330, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brian/work/tests/registry_with_parent.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/brian/work/protocol-ri/mplane/model.py", line 1252, in test_registry
    test_registry = Registry("../tests/registry_with_parent.json")
  File "/Users/brian/work/protocol-ri/mplane/model.py", line 1610, in __init__
    self._parse_from_uri(self._uri)
  File "/Users/brian/work/protocol-ri/mplane/model.py", line 1667, in _parse_from_uri
    with urllib.request.urlopen(uri) as stream:
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1308, in file_open
    return self.open_local_file(req)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1348, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/Users/brian/work/tests/registry_with_parent.json'>

----------------------------------------------------------------------

**Comment by britram** [comment]
@cimere I'm going to go ahead and merge the test branch into sdk. Is there anything in sdk-test-certs that needs to be merged into sdk-test first?

**Comment by cimere** [comment]
Nope. That branch can be deleted.

Thanks
Ciro
________________________________
Da: Brian Trammell<mailto:notifications@github.com>
Inviato: ‎16/‎02/‎2015 12:51
A: fp7mplane/protocol-ri<mailto:protocol-ri@noreply.github.com>
Cc: cimere<mailto:ciro.meregalli@gmail.com>
Oggetto: Re: [protocol-ri] Implement unit test coverage (#19)

@cimere I'm going to go ahead and merge the test branch into sdk. Is there anything in sdk-test-certs that needs to be merged into sdk-test first?

---

**Comment by britram** [comment]
I'm working to merge the sdk-tests branch back into sdk; I'm moivng tests/tests.py to mplane/tests.py, and renaming tests to testdata. I'll also move bare model tests back out of the model into tests.py.

In reviewing tests.py, there are bits of code causing stateful side-effects that are run on import, which might not work in all cases; I'm modifying these as well.

Thanks!

**Comment by britram** [comment]
Merged into SDK branch, sdk-tests and tests-certs branches deleted.
