### ISSUE TITLE
Tests fail on sdk branch

### ISSUE THREAD

**Issue by britram** [fp7mplane/protocol-ri#29]
```
-> briant@nb-10604 in ~/work/protocol-ri on git:sdk o [14:11:09]
% nosetests mplane
EE...........
======================================================================
ERROR: mplane.tests.test_Authorization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/briant/work/protocol-ri/mplane/tests.py", line 68, in test_Authorization
    res_auth = azn.Authorization(config_path)
  File "/Users/briant/work/protocol-ri/mplane/azn.py", line 30, in Authorization
    if "TLS" not in config.sections():
AttributeError: 'str' object has no attribute 'sections'

======================================================================
ERROR: mplane.tests.test_AuthorizationOn
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/briant/work/protocol-ri/mplane/tests.py", line 77, in test_AuthorizationOn
    res = azn.AuthorizationOn(config_path)
  File "/Users/briant/work/protocol-ri/mplane/azn.py", line 45, in __init__
    self.id_role = self._load_roles(config["Roles"])
TypeError: string indices must be integers

----------------------------------------------------------------------
```

**Comment by britram** [comment]
Both of these appear to be related to an incompatible API change: azn.Authorization used to take a configuration file name, now it takes a parsed configuration. The best way to fix this is most probably to change the tests to conform to the new API.
