### ISSUE TITLE
mplane.model.render_text not working with Exceptions

### ISSUE THREAD

**Issue by stepenta** [fp7mplane/protocol-ri#32]
When a measurement goes wrong and the component returns an exception, the command in the clientshell: showmeas <token> (where token is the token of the exception)
gives the following error :

An exception occurred:
'Exception' object has no attribute 'kind_str'
You can try to continue, but client state may be inconsistent.

**Comment by stepenta** [comment]
Still not working, new error is: 
'Exception' object has no attribute 'verb'

**Comment by britram** [comment]
Can you paste a backtrace here?

**Comment by stepenta** [comment]
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stefanop/Scrivania/mplane/git/protocol-ri/mplane/clientshell.py", line 497, in <module>
    cs.cmdloop()
  File "/usr/lib64/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/stefanop/Scrivania/mplane/git/protocol-ri/mplane/clientshell.py", line 428, in do_showmeas
    mplane.model.render_text(res)
  File "/home/stefanop/Scrivania/mplane/git/protocol-ri/mplane/model.py", line 3062, in render_text
    print(render(message))
  File "/home/stefanop/Scrivania/mplane/git/protocol-ri/mplane/model.py", line 3066, in render
    out = "%s: %s\n" % (msg.kind_str(), msg.verb())
AttributeError: 'Exception' object has no attribute 'verb'

**Comment by britram** [comment]
Ah, okay I see. While `kind_str()` was definitely missing in `mplane.model.Exception`, there's also the fact than render_text is not quite finished. Oops. :/ My bad, fix coming shortly...

**Comment by britram** [comment]
have a look at 774ed0e on sdk, merge to master if that works.

**Comment by stepenta** [comment]
I fixed a couple of typos and committed, the output now is:

|mplane| showmeas 34f4f1c3a9a6e925316cd1dd158185a1
exception: 34f4f1c3a9a6e925316cd1dd158185a1
    message     : list index out of range

If that's ok for you, we're ready to merge

**Comment by britram** [comment]
Merged this back; master and SDK are synced now. Closing.
