### ISSUE TITLE
mpcom/mpcli configuration robustness

### ISSUE THREAD

**Issue by britram** [fp7mplane/protocol-ri#42]
First, mpcli should never crash or fail to start based on a missing key in the configuration file. 
mpcom should only require a single component section in the configuration file to start. All other configuration keys should have sensible defaults.Runtime code should detect missing keys. 

I've fixed most of this problem in the SDK branch. The only key I know of with this problem now is the source_ip key.

Configuration access should to the extent possible operate such that the configuration object can be replaced with a two-level hash: the in operator should be used to check for membership, and access to values should always use the index [] operator. Specifically, config.getint("foo", "bar") should always be replaced by int(config['foo']['bar']).

This problem doesn't exist in the current SDK codebase.

**Comment by stepenta** [comment]
source_ip is not there anymore, see #43

**Comment by britram** [comment]
The right thing to do here is start from scratch, build configuration documentation (for a configuration file format based on JSON, for consistency), then implement that.

We won't get to this for the SDK (or, probably, even for the demo). Deferring.

**Comment by britram** [comment]
Crashing on startup with an existing config because someone added a new configuration key is **not acceptable**; cf:

```
Traceback (most recent call last):
  File "scripts/mpcom", line 52, in <module>
    component = mplane.component.ListenerHttpComponent(config)
  File "/Users/briant/work/protocol-ri/mplane/component.py", line 96, in __init__
    super(ListenerHttpComponent, self).__init__(config)
  File "/Users/briant/work/protocol-ri/mplane/component.py", line 69, in __init__
    service.set_capability_link(config["component"]["listen-cap-link"])
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/configparser.py", line 1203, in __getitem__
    raise KeyError(key)
KeyError: 'listen-cap-link'
```

If you add a configuration key somewhere, you **must** make sure you add a reasonable default for a missing key.

**Comment by britram** [comment]
Refactoring code to take JSON-based configuration happens in the json-conf branch.

**Comment by britram** [comment]
(Thanks @stepenta!!)
