### ISSUE TITLE
Zero values parameter error

### ISSUE THREAD

**Issue by ekorian** [fp7mplane/protocol-ri#51]
Setting a parameter value to zero whether it's a real, a natural or a boolean parameter always ends up with an error on the supervisor output independently of the constraint ("0 ... 255","*", "0, 1").
e.g:
Got exception in _run(), returning <Exception: e95ba946509eb2fc3318581b3db4c212 'missing parameter scamper.ping.tos'>

**Comment by britram** [comment]
Would it be possible to add the full stack trace to this issue?

**Comment by ekorian** [comment]
Sure

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ko/Desktop/2015/Vienna/test/protocol-ri/mplane/scheduler.py", line 134, in _run
    self._check_interrupt)
  File "/home/ko/Desktop/2015/Vienna/test/protocol-ri/mplane/supervisor.py", line 51, in run
    fwd_spec = self._client.invoke_capability(trunc_label, spec.when(), spec.parameter_values())
  File "/home/ko/Desktop/2015/Vienna/test/protocol-ri/mplane/client.py", line 666, in invoke_capability
    (cap, spec) = self._spec_for(cap_tol, when, params, relabel)
  File "/home/ko/Desktop/2015/Vienna/test/protocol-ri/mplane/client.py", line 194, in _spec_for
    raise KeyError("missing parameter "+pname)
KeyError: 'missing parameter scamper.ping.rr'

**Comment by britram** [comment]
This seems like a check against true where there should be a check against None.

**Comment by britram** [comment]
Cannot reproduce with loopback test with empty string (which would also fail such a check): @ekorian, let's take a look at this in Milan next week.
